export const videoData = [
    {
        id: 1,
        thumbnail: "https://i.ytimg.com/vi/3JZ_D3ELwOQ/maxresdefault.jpg",
        title: "The Future of AI in 2025",
        channel: "Tech World",
        views: "1.2M views",
        timestamp: "2 weeks ago",
    },
    {
        id: 2,
        thumbnail: "https://i.ytimg.com/vi/aqz-KE-bpKQ/maxresdefault.jpg",
        title: "Exploring the Amazon Rainforest",
        channel: "WildLife Channel",
        views: "850K views",
        timestamp: "1 month ago",
    },
    {
        id: 3,
        thumbnail: "https://i.ytimg.com/vi/tgbNymZ7vqY/maxresdefault.jpg",
        title: "NASA's Latest Mars Mission Update",
        channel: "NASA Official",
        views: "2.5M views",
        timestamp: "3 days ago",
    },
    {
        id: 4,
        thumbnail: "https://i.ytimg.com/vi/LXb3EKWsInQ/maxresdefault.jpg",
        title: "Top 10 Supercars of 2024",
        channel: "Car Lovers",
        views: "900K views",
        timestamp: "2 weeks ago",
    },
    {
        id: 5,
        thumbnail: "https://i.ytimg.com/vi/VYOjWnS4cMY/maxresdefault.jpg",
        title: "Easy 5-Minute Recipes",
        channel: "Tasty Bites",
        views: "1.1M views",
        timestamp: "5 days ago",
    },
    {
        id: 6,
        thumbnail: "https://i.ytimg.com/vi/Zi_XLOBDo_Y/maxresdefault.jpg",
        title: "Best Games to Play in 2024",
        channel: "Gamer Hub",
        views: "3.2M views",
        timestamp: "1 day ago",
    },
    {
        id: 7,
        thumbnail: "https://i.ytimg.com/vi/2Vv-BfVoq4g/maxresdefault.jpg",
        title: "10-Minute Home Workout",
        channel: "FitLife",
        views: "720K views",
        timestamp: "1 month ago",
    },
    {
        id: 8,
        thumbnail: "https://i.ytimg.com/vi/MwpMEbgC7DA/maxresdefault.jpg",
        title: "Master React in 2024",
        channel: "CodeWithMe",
        views: "1.7M views",
        timestamp: "2 weeks ago",
    },
    {
        id: 9,
        thumbnail: "https://i.ytimg.com/vi/1nO_z-CHnMo/maxresdefault.jpg",
        title: "Top 10 Travel Destinations",
        channel: "Wanderlust",
        views: "980K views",
        timestamp: "4 days ago",
    },
    {
        id: 10,
        thumbnail: "https://i.ytimg.com/vi/9bZkp7q19f0/maxresdefault.jpg",
        title: "Relaxing Jazz Music",
        channel: "Chill Vibes",
        views: "2M views",
        timestamp: "3 weeks ago",
    },
];
